### ISSUE TITLE
nemo-media-columns: Segfault with images

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo-extensions#265]
I am experiencing the same segfaults as mentioned in #58 and as per instructions I have created a new issue.
I have tested it with the provided test image from the other report and was able to reproduce it reliably, including other images of my own.

Nemo version: 3.6.5
Nemo-media-columns version: latest from master branch

```
Core was generated by `nemo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f51591f661c in ?? () from /usr/lib/libexiv2.so.26
[Current thread is 1 (Thread 0x7f517b04d9c0 (LWP 3139))]
#0  0x00007f51591f661c in  () at /usr/lib/libexiv2.so.26
#1  0x00007f51591d0d8d in  () at /usr/lib/libexiv2.so.26
#2  0x00007f51591bfc85 in TXMPMeta<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RegisterNamespace(char const*, char const*) () at /usr/lib/libexiv2.so.26
#3  0x00007f51591bb2f8 in Exiv2::XmpParser::initialize(void (*)(void*, bool), void*) () at /usr/lib/libexiv2.so.26
#4  0x00007f51591bdd8a in Exiv2::XmpParser::decode(Exiv2::XmpData&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /usr/lib/libexiv2.so.26
#5  0x00007f5159124642 in Exiv2::JpegBase::readMetadata() () at /usr/lib/libexiv2.so.26
#6  0x00007f5159794172 in exiv2wrapper::Image::readMetadata() () at /usr/lib/python2.7/site-packages/libexiv2python.so
#7  0x00007f51597a0bc6 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (exiv2wrapper::Image::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, exiv2wrapper::Image&> > >::operator()(_object*, _object*) () at /usr/lib/python2.7/site-packages/libexiv2python.so
#8  0x00007f515954311d in boost::python::objects::function::call(_object*, _object*) const () at /usr/lib/libboost_python.so.1.66.0
#9  0x00007f51595432d9 in  () at /usr/lib/libboost_python.so.1.66.0
#10 0x00007f515954a0eb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () at /usr/lib/libboost_python.so.1.66.0
#11 0x00007f51597a0234 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Exiv2::BasicError<char>, void (*)(Exiv2::BasicError<char> const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Exiv2::BasicError<char> const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () at /usr/lib/python2.7/site-packages/libexiv2python.so
#12 0x00007f5159549e6f in boost::python::handle_exception_impl(boost::function0<void>) () at /usr/lib/libboost_python.so.1.66.0
#13 0x00007f515954090a in  () at /usr/lib/libboost_python.so.1.66.0
#14 0x00007f516917b573 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#15 0x00007f516915d6ae in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#16 0x00007f5169158550 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#17 0x00007f5169158550 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#18 0x00007f51691b2456 in PyEval_EvalCodeEx () at /usr/lib/libpython2.7.so.1.0
#19 0x00007f516914e11f in function_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#20 0x00007f516917b573 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#21 0x00007f516913c93f in instancemethod_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#22 0x00007f516917b573 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#23 0x00007f51691b1b31 in PyEval_CallObjectWithKeywords () at /usr/lib/libpython2.7.so.1.0
#24 0x00007f51689fe72d in  () at /usr/lib/python2.7/site-packages/gi/_gi.so
#25 0x00007f517238dfbf in ffi_closure_unix64_inner () at /usr/lib/libffi.so.6
#26 0x00007f517238e330 in ffi_closure_unix64 () at /usr/lib/libffi.so.6
#27 0x00007f5177c04ca6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#28 0x00007f5177c05081 in  () at /usr/lib/libglib-2.0.so.0
#29 0x00007f5177c0510e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#30 0x00007f51781ca96e in g_application_run () at /usr/lib/libgio-2.0.so.0
#31 0x000055a6d2c45c12 in  ()
#32 0x00007f5176cabf4a in __libc_start_main () at /usr/lib/libc.so.6
#33 0x000055a6d2c45c6a in  ()
```

**Comment by dglava** [comment]
Works as of 4.4.0.
