### ISSUE TITLE
nemo-media-columns 3.6.0-1 segfault

### ISSUE THREAD

**Issue by CNG** [linuxmint/nemo-extensions#272]
My Nemo crashes instantly upon opening apparently any of my images folders. I am on Arch Linux and have these packages installed:

```
$ pacman -Q | grep nemo
nemo-git lmde3.r0.gd28e98bf-1
nemo-media-columns 3.6.0-1
nemo-python 3.6.0-2
```

I think this is the same or similar to https://github.com/linuxmint/nemo-extensions/issues/58 and https://github.com/linuxmint/nemo-extensions/issues/265 from a quick glance. I tried following the directions on [getting traces in Arch](https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces), so hopefully the following is helpful in some way:

```
Thread 16 (Thread 0x7fffccd25700 (LWP 13258)):
#0  0x00007ffff3d28879 in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff596352d in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff58ee903 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5945436 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5944a2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7fffbffff700 (LWP 13257)):
#0  0x00007ffff3d28879 in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff596352d in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff58ee903 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5945436 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5944a2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fffce1a5700 (LWP 12767)):
#0  0x00007ffff3d28879 in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff596352d in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff58ee903 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5945436 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5944a2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fffbd5cf700 (LWP 12514)):
#0  0x00007ffff3d2397b in poll () at /usr/lib/libc.so.6
#1  0x00007fffbe225773 in  () at /usr/lib/libpulse.so.0
#2  0x00007fffbe216bd0 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fffbe217271 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fffbe217301 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fffbe2256ae in  () at /usr/lib/libpulse.so.0
#6  0x00007fffbdfc481c in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe37fe700 (LWP 12468)):
#0  0x00007ffff3d2397b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff591c523 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff591c63e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffe81aff4e in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff5944a2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffe3fff700 (LWP 12467)):
#0  0x00007ffff3d2397b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff591c523 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff591c8e2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5f0b348 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff5944a2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe8bb6700 (LWP 12466)):
#0  0x00007ffff3d2397b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff591c523 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff591c63e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff591c692 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5944a2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3ff608c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3d2de7f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f919c0 (LWP 12432)):
#0  0x00007fffd1a27a0c in XMPMeta::RegisterNamespace(char const*, char const*) (namespaceURI=namespaceURI@entry=0x7fffd1a7f058 "http://ns.adobe.com/lightroom/1.0/", prefix=prefix@entry=0x7fffd1a88c94 "lr")
    at /home/cgorichanaz/temp/exiv2/repos/extra-x86_64/src/exiv2-0.26/xmpsdk/src/XMPMeta.cpp:1048
        nsURI = "http://ns.adobe.com/lightroom/1.0/"
        prfix = "lr:"
#1  0x00007fffd1a01dbd in WXMPMeta_RegisterNamespace_1(XMP_StringPtr, XMP_StringPtr, WXMP_Result*) (namespaceURI=0x7fffd1a7f058 "http://ns.adobe.com/lightroom/1.0/", prefix=0x7fffd1a88c94 "lr", wResult=0x7fffffffcbf0)
    at /home/cgorichanaz/temp/exiv2/repos/extra-x86_64/src/exiv2-0.26/xmpsdk/src/WXMPMeta.cpp:228
#2  0x00007fffd19f1035 in TXMPMeta<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RegisterNamespace(char const*, char const*) (namespaceURI=namespaceURI@entry=0x7fffd1a7f058 "http://ns.adobe.com/lightroom/1.0/", prefix=prefix@entry=0x7fffd1a88c94 "lr") at /home/cgorichanaz/temp/exiv2/repos/extra-x86_64/src/exiv2-0.26/xmpsdk/include/client-glue/TXMPMeta.incl_cpp:240
        wResult = {errMessage = 0x0, ptrResult = 0x0, floatResult = 0, int64Result = 0, int32Result = 93823560581121}
#3  0x00007fffd19ec6a8 in Exiv2::XmpParser::initialize(void (*)(void*, bool), void*) (xmpLockFct=xmpLockFct@entry=0x0, pLockData=pLockData@entry=0x0) at /home/cgorichanaz/temp/exiv2/repos/extra-x86_64/src/exiv2-0.26/src/xmp.cpp:404
#4  0x00007fffd19ef13a in Exiv2::XmpParser::decode(Exiv2::XmpData&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (xmpData=..., xmpPacket="<?xpacket begin=\"﻿\" id=\"W5M0MpCehiHzreSzNTczkc9d\"?> <x:xmpmeta xmlns:x=\"adobe:ns:meta/\" x:xmptk=\"Adobe XMP Core 5.6-c128 79.159124, 2016/03/18-14:01:55        \"> <rdf:RDF xmlns:rdf=\"http://www.w3.or"...)
    at /home/cgorichanaz/temp/exiv2/repos/extra-x86_64/src/exiv2-0.26/src/xmp.cpp:546
        iter = {_vptr.TXMPIterator = 0x7fffffffce60, iterRef = 0x5555566ffc10}
        schemaNs = <error: Cannot access memory at address 0x11>
        propPath = Python Exception <class 'OverflowError'> int too big to convert: 

        opt = 140736713648816
        meta = {_vptr.TXMPMeta = 0x5555566c7b80, xmpRef = 0x7fffffffce00}
        propValue = <error: Cannot access memory at address 0x8282>
#5  0x00007fffd1954822 in Exiv2::JpegBase::readMetadata() (this=0x5555566c7b70)
    at /home/cgorichanaz/temp/exiv2/repos/extra-x86_64/src/exiv2-0.26/src/jpgimage.cpp:409
        xmpPacket = 
          {pData_ = 0x55555683d0e0 "<?xpacket begin=\"﻿\" id=\"W5M0MpCehiHzreSzNTczkc9d\"?> <x:xmpmeta xmlns:x=\"adobe:ns:meta/\" x:xmptk=\"Adobe XMP Core 5.6-c128 79.159124, 2016/03/18-14:01:55        \"> <rdf:RDF xmlns:rdf=\"http://www.w3.or"..., size_ = 3627}
        size = 3658
        rc = 0
        closer = {_vptr.IoCloser = 0x7fffd1d250d8 <vtable for Exiv2::IoCloser+16>, bio_ = @0x5555564c86a0}
        search = 5
        bufMinSize = 36
        bufRead = <optimized out>
        buf = {pData_ = 0x7fffb802b690 "\016Jhttp://ns.adobe.com/xap/1.0/", size_ = 36}
        psBlob = std::vector of length 0, capacity 0
        foundCompletePsData = false
        foundExifData = true
        foundXmpData = false
        foundIccData = false
        marker = <optimized out>
#6  0x00007fffd2007172 in exiv2wrapper::Image::readMetadata() () at /usr/lib/python2.7/site-packages/libexiv2python.so
#7  0x00007fffd2013bc6 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (exiv2wrapper::Image::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, exiv2wrapper::Image&> > >::operator()(_object*, _object*) ()
    at /usr/lib/python2.7/site-packages/libexiv2python.so
#8  0x00007fffd1d7511d in boost::python::objects::function::call(_object*, _object*) const () at /usr/lib/libboost_python.so.1.66.0
#9  0x00007fffd1d752d9 in  () at /usr/lib/libboost_python.so.1.66.0
#10 0x00007fffd1d7c0eb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const ()
    at /usr/lib/libboost_python.so.1.66.0
#11 0x00007fffd2013234 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Exiv2::BasicError<char>, void (*)(Exiv2::BasicError<char> const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Exiv2::BasicError<char> const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) ()
    at /usr/lib/python2.7/site-packages/libexiv2python.so
#12 0x00007fffd1d7be6f in boost::python::handle_exception_impl(boost::function0<void>) () at /usr/lib/libboost_python.so.1.66.0
#13 0x00007fffd1d7290a in  () at /usr/lib/libboost_python.so.1.66.0
#14 0x00007fffe1a6d573 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#15 0x00007fffe1a4f6ae in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#16 0x00007fffe1a4a550 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#17 0x00007fffe1a4a550 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#18 0x00007fffe1aa4456 in PyEval_EvalCodeEx () at /usr/lib/libpython2.7.so.1.0
#19 0x00007fffe1a4011f in function_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#20 0x00007fffe1a6d573 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#21 0x00007fffe1a2e93f in instancemethod_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#22 0x00007fffe1a6d573 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#23 0x00007fffe1aa3b31 in PyEval_CallObjectWithKeywords () at /usr/lib/libpython2.7.so.1.0
#24 0x00007fffe132f87e in  () at /usr/lib/python2.7/site-packages/gi/_gi.so
#25 0x00007fffef95afbf in ffi_closure_unix64_inner () at /usr/lib/libffi.so.6
#26 0x00007fffef95b330 in ffi_closure_unix64 () at /usr/lib/libffi.so.6
#27 0x00007ffff591c1d6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff591c5b1 in  () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff591c63e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff5edd97e in g_application_run () at /usr/lib/libgio-2.0.so.0
#31 0x00005555555808a2 in main (argc=1, argv=0x7fffffffe2c8) at ../src/nemo-main.c:104
        retval = <optimized out>
        application = 0x555555939130

```

**Comment by pie3636** [comment]
Same issue, similar stacktrace:

```
Stack trace of thread 17333:
#0  0x00007fb2431dc61c n/a (libexiv2.so.26)
#1  0x00007fb2431b6d8d n/a (libexiv2.so.26)
#2  0x00007fb2431a5c85 _ZN8TXMPMetaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE17RegisterNamespaceEPKcS8_ (libexiv2.so.26)
#3  0x00007fb2431a12f8 _ZN5Exiv29XmpParser10initializeEPFvPvbES1_ (libexiv2.so.26)
#4  0x00007fb2431a3d8a _ZN5Exiv29XmpParser6decodeERNS_7XmpDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (libexiv2.so.26)
#5  0x00007fb24310a642 _ZN5Exiv28JpegBase12readMetadataEv (libexiv2.so.26)
#6  0x00007fb24c313a82 _ZN12exiv2wrapper5Image12readMetadataEv (libexiv2python.so)
#7  0x00007fb24c31b907 _ZN5boost6python7objects23caller_py_function_implINS0_6detail6callerIMN12exiv2wrapper5ImageEFvvENS0_21default_call_policiesENS_3mpl7vector2IvRS6_EEEEEclEP7_objectSH_ (libexiv2python.so)
#8  0x00007fb24c2795dd _ZNK5boost6python7objects8function4callEP7_objectS4_ (libboost_python27.so.1.68.0)
#9  0x00007fb24c2797c9 n/a (libboost_python27.so.1.68.0)
#10 0x00007fb24c28066b _ZNK5boost6python6detail17exception_handlerclERKNS_9function0IvEE (libboost_python27.so.1.68.0)
#11 0x00007fb24c31b524 _ZN5boost6detail8function21function_obj_invoker2INS_3_bi6bind_tIbNS_6python6detail19translate_exceptionIN5Exiv210BasicErrorIcEEPFvRKSA_EEENS3_5list3INS_3argILi1EEENSH_ILi2EEENS3_5valueISE_EEEEEEbRKNS6_17exception_handlerERKNS_9function0IvEEE6invokeERNS1_15function_bufferESQ_SU_ (libexiv2python.so)
#12 0x00007fb24c28053f _ZN5boost6python21handle_exception_implENS_9function0IvEE (libboost_python27.so.1.68.0)
#13 0x00007fb24c277e77 n/a (libboost_python27.so.1.68.0)
#14 0x00007fb24e8390e3 PyObject_Call (libpython2.7.so.1.0)
#15 0x00007fb24e89a80e PyEval_EvalFrameEx (libpython2.7.so.1.0)
#16 0x00007fb24e8959d0 PyEval_EvalFrameEx (libpython2.7.so.1.0)
#17 0x00007fb24e8959d0 PyEval_EvalFrameEx (libpython2.7.so.1.0)
#18 0x00007fb24e8f00da PyEval_EvalCodeEx (libpython2.7.so.1.0)
#19 0x00007fb24e881e0f function_call.lto_priv.233 (libpython2.7.so.1.0)
#20 0x00007fb24e8390e3 PyObject_Call (libpython2.7.so.1.0)
#21 0x00007fb24e8a549f instancemethod_call.lto_priv.148 (libpython2.7.so.1.0)
#22 0x00007fb24e8390e3 PyObject_Call (libpython2.7.so.1.0)
#23 0x00007fb24e8ef7d1 PyEval_CallObjectWithKeywords (libpython2.7.so.1.0)
#24 0x00007fb24e4fd7a4 n/a (_gi.so)
#25 0x00007fb25a529fbf ffi_closure_unix64_inner (libffi.so.6)
#26 0x00007fb25a52a330 ffi_closure_unix64 (libffi.so.6)
#27 0x00007fb25dc86271 g_main_context_dispatch (libglib-2.0.so.0)
#28 0x00007fb25dc87f89 n/a (libglib-2.0.so.0)
#29 0x00007fb25dc87fce g_main_context_iteration (libglib-2.0.so.0)
#30 0x00007fb25de2c7ee g_application_run (libgio-2.0.so.0)
#31 0x00005572e01a5142 n/a (nemo)
#32 0x00007fb25cd54223 __libc_start_main (libc.so.6)
#33 0x00005572e01a518e n/a (nemo)

Stack trace of thread 17340:
#0  0x00007fb25ce20bb1 __poll (libc.so.6)
#1  0x00007fb25dc87ee0 n/a (libglib-2.0.so.0)
#2  0x00007fb25dc87fce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fb25dc88022 n/a (libglib-2.0.so.0)
#4  0x00007fb25dc513eb n/a (libglib-2.0.so.0)
#5  0x00007fb25cefba9d start_thread (libpthread.so.0)
#6  0x00007fb25ce2ba43 __clone (libc.so.6)

Stack trace of thread 17341:
#0  0x00007fb25ce20bb1 __poll (libc.so.6)
#1  0x00007fb25dc87ee0 n/a (libglib-2.0.so.0)
#2  0x00007fb25dc88f62 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007fb25ddedc28 n/a (libgio-2.0.so.0)
#4  0x00007fb25dc513eb n/a (libglib-2.0.so.0)
#5  0x00007fb25cefba9d start_thread (libpthread.so.0)
#6  0x00007fb25ce2ba43 __clone (libc.so.6)

Stack trace of thread 17358:
#0  0x00007fb25ce2640d syscall (libc.so.6)
#1  0x00007fb25dc36f61 g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fb25dcb4cb3 n/a (libglib-2.0.so.0)
#3  0x00007fb25dc58d2b n/a (libglib-2.0.so.0)
#4  0x00007fb25dc513eb n/a (libglib-2.0.so.0)
#5  0x00007fb25cefba9d start_thread (libpthread.so.0)
#6  0x00007fb25ce2ba43 __clone (libc.so.6)

Stack trace of thread 17342:
#0  0x00007fb25ce20bb1 __poll (libc.so.6)
#1  0x00007fb25dc87ee0 n/a (libglib-2.0.so.0)
#2  0x00007fb25dc87fce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fb25435ebde n/a (libdconfsettings.so)
#4  0x00007fb25dc513eb n/a (libglib-2.0.so.0)
#5  0x00007fb25cefba9d start_thread (libpthread.so.0)
#6  0x00007fb25ce2ba43 __clone (libc.so.6)

Stack trace of thread 17365:
#0  0x00007fb25ce2640d syscall (libc.so.6)
#1  0x00007fb25dc36f61 g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fb25dcb4cb3 n/a (libglib-2.0.so.0)
#3  0x00007fb25dc58d2b n/a (libglib-2.0.so.0)
#4  0x00007fb25dc513eb n/a (libglib-2.0.so.0)
#5  0x00007fb25cefba9d start_thread (libpthread.so.0)
#6  0x00007fb25ce2ba43 __clone (libc.so.6)

Stack trace of thread 17351:
#0  0x00007fb25ce20bb1 __poll (libc.so.6)
#1  0x00007fb223de2673 n/a (libpulse.so.0)
#2  0x00007fb223dd3990 pa_mainloop_poll (libpulse.so.0)
#3  0x00007fb223dd3fe0 pa_mainloop_iterate (libpulse.so.0)
#4  0x00007fb223dd4091 pa_mainloop_run (libpulse.so.0)
#5  0x00007fb223de25ae n/a (libpulse.so.0)
#6  0x00007fb223b819fc n/a (libpulsecommon-12.2.so)
#7  0x00007fb25cefba9d start_thread (libpthread.so.0)
#8  0x00007fb25ce2ba43 __clone (libc.so.6)
```
