### ISSUE TITLE
[nemo-terminal] Terminal will not follow Nemo into folders with japanese characters

### ISSUE THREAD

**Issue by Essoje** [linuxmint/nemo-extensions#328]
Hello, I'm running Nemo under Manjaro kernel 5.1.15-1 and Cinnamon 4.2.0.

Whenever I attempt to navigate a folder with japanese characters, nemo will enter the folder without trouble but nemo-terminal will simply refuse to do so automatically. Manually using cd to enter the folder works fine.
I've only started using nemo-terminal recently so I wouldn't know if it worked in the past.
I also modified the 'Change Directory Command' to just 'cd %s' in order to see what it would output, which shows normal ASCII paths normally but there was no output (not even a 'cd ') when there's japanese in the path.

**Comment by RavetcoFX** [comment]
Does the terminal button you can enable in the toolbar work?

**Comment by Essoje** [comment]
If you mean the 'Open a terminal in the active folder' button, then yes, it does open the folder correctly in a separate terminal window.

**Comment by RavetcoFX** [comment]
I couldn't replicate this, are you using the 4.2.0 version of the extension or the version from git?
The text I tested with for the folder I named テスト which was google translate "Test" to Japanese
Are you using UTF-8?
![image](https://user-images.githubusercontent.com/1816681/61485519-98f93680-a95e-11e9-8fd0-504fe3876dbd.png)

**Comment by RavetcoFX** [comment]
I couldn't replicate this, are you using the 4.2.0 version of the extension or the version from git?
The text I tested with for the folder I named テスト which was google translate "Test" to Japanese
Are you using UTF-8?
![image](https://user-images.githubusercontent.com/1816681/61485519-98f93680-a95e-11e9-8fd0-504fe3876dbd.png)

**Comment by Essoje** [comment]
UTF-8 as well. And Manjaro's package I use has a build time of 06/23/2019, the same as the latest git date for terminal.
I've created a テスト folder directly in my home folder just to have some consistent testing and the result is that nemo still won't follow it.
![Screenshot from 2019-07-18 18-53-02](https://user-images.githubusercontent.com/5125305/61494755-6a468480-a98d-11e9-909e-70041ca218a4.png)

**Comment by RavetcoFX** [comment]
in a new terminal can you run "killall nemo; nemo" try again and see if you get any output?

**Comment by Essoje** [comment]
This is the result from when I attempt to enter any japanese folder:
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 472, in _on_crowbar_parent_set
    nterm.change_directory(self._uri)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 251, in change_directory
    self.feed_child(cdcmd)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 413, in feed_child
    self.term.feed_child(text.encode())
OverflowError: Item 16: 227 not in range -128 to 127

**Comment by RavetcoFX** [comment]
Looks like you're somehow using an encoding method based on UTF16 instead of UTF8, I should have a fix shortly

**Comment by RavetcoFX** [comment]
Nevermind, I found text that causes the same crash

`Power
لُلُصّبُلُلصّبُررً ॣ ॣh ॣ ॣ
冗`

**Comment by RavetcoFX** [comment]
@Essoje please try this branch, it should work
https://github.com/RavetcoFX/nemo-extensions/tree/unicode-fix

**Comment by Essoje** [comment]
Branch makes it so it stops following all folders indiscriminately.
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 409, in feed_child
    self.term.feed_child(item.decode())
TypeError: Item 0: Must be number, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 465, in _on_crowbar_parent_set
    nterm.change_directory(self._uri)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 244, in change_directory
    self.feed_child(eraselinekeys.encode().decode("unicode_escape"))
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 411, in feed_child
    self.term.feed_child(item.decode(), len(item))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

**Comment by mtwebster** [comment]
Can you check what version of nemo-terminal you're using?  I do get an error in 4.2, but it's related to the magic that cleans up the terminal prompt after changing directories.  Actually changing directories works, though.

**Comment by RavetcoFX** [comment]
@Essoje ok added some exceptions again, this should work now https://github.com/RavetcoFX/nemo-extensions/commits/unicode-fix

**Comment by Essoje** [comment]
@mtwebster
Manjaro uses the git version. I also double-checked the commit date and it is the same date as the last nemo-terminal. Nemo was updated yesterday to 4.2.1.

@RavetcoFX 
Now goes back to original problem. Not sure how to do this in python, but might want to check how the path is being changed after each call?
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 475, in _on_crowbar_parent_set
    nterm.change_directory(self._uri)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 251, in change_directory
    self.feed_child(cdcmd)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 413, in feed_child
    self.term.feed_child(item)
OverflowError: Item 16: 227 not in range -128 to 127

**Comment by RavetcoFX** [comment]
@Essoje Ok, made another change to see if its utf16 https://github.com/RavetcoFX/nemo-extensions/commits/unicode-fix

**Comment by Essoje** [comment]
@RavetcoFX 
Result:
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 413, in feed_child
    self.term.feed_child(item)
OverflowError: Item 16: 227 not in range -128 to 127

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 487, in _on_crowbar_parent_set
    nterm.change_directory(self._uri)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 251, in change_directory
    self.feed_child(cdcmd)
  File "/usr/share/nemo-python/extensions/nemo_terminal.py", line 425, in feed_child
    self.term.feed_child(item)
OverflowError: 255 not in range -128 to 127

**Comment by RavetcoFX** [comment]
@Essoje ok, in the terminal can you try one of these commands "locale charmap", "echo $LC_CTYPE", "echo $LANG" so we can see exactly what your character encoding is?

**Comment by Essoje** [comment]
@RavetcoFX They return UTF-8, blank and en_US.UTF8 in that order.
If it matters, locale -a also returns: C, en_US.utf8, es_US.utf8, ja_JP, ja_JP.eucjp, ja_JP.ujis, ja_JP.utf8, japanese, japanese.euc, POSIX, pt_BR.utf8. As far as I know, they are only used if I invoke them with something like LC_ALL, so they should not be creating any trouble in this case.

**Comment by RavetcoFX** [comment]
@Essoje can you check in your package manager what version you have installed of VTE?

**Comment by Essoje** [comment]
@RavetcoFX Manjaro's vte3 package has vte 2.91 in it.
