### ISSUE TITLE
nemo-compare.py: NameError: name '_' is not defined

### ISSUE THREAD

**Issue by claudiux** [linuxmint/nemo-extensions#517]
This message appears in `~/.xsession-errors`:

```
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-compare.py", line 168, in get_name_and_desc
    description = _("Allows file comparison from the context menu")
NameError: name '_' is not defined
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-compare.py", line 168, in get_name_and_desc
    description = _("Allows file comparison from the context menu")
NameError: name '_' is not defined
```

**Comment by leigh123linux** [comment]
Duplicate of #513
