### ISSUE TITLE
Crash of nemo-media-columns on images with XMP metadata.

### ISSUE THREAD

**Issue by kupiakos** [linuxmint/nemo-extensions#58]
Nemo is crashing with nemo-media-columns while navigating to directories containing certain PNG and JPG files. Attached is one such PNG that causes a problem. 
![eclipse-800x426](https://cloud.githubusercontent.com/assets/3309728/3438708/ba0a9860-00cf-11e4-91e2-d1765e0ed7ab.png)

I'm using Arch Linux, nemo 2.2.2, cinnamon 2.2.13, exempi 2.2.1-2, nemo-media-columns 2.2.0-1, and the `3.15.2-1-ARCH` kernel.

Running `exempi` on known "good" and "bad" images shows that it fails on images with XMP metadata. `exempi` does not crash, and neither does `eog`, which depends on libexempi.

Result of gdb backtrace of nemo crash:

```
#0  0x00007ffff4aaaa5e in WXMPMeta_RegisterNamespace_1 () from /usr/lib/libexempi.so.3
#1  0x00007fffd2b54994 in TXMPMeta<std::string>::RegisterNamespace(char const*, char const*) () from /usr/lib/libexiv2.so.13
#2  0x00007fffd2b4f2f6 in Exiv2::XmpParser::initialize(void (*)(void*, bool), void*) () from /usr/lib/libexiv2.so.13
#3  0x00007fffd2b52038 in Exiv2::XmpParser::decode(Exiv2::XmpData&, std::string const&) () from /usr/lib/libexiv2.so.13
#4  0x00007fffd2b5b7d6 in Exiv2::Internal::PngChunk::parseChunkContent(Exiv2::Image*, unsigned char const*, long, Exiv2::DataBuf) ()
   from /usr/lib/libexiv2.so.13
#5  0x00007fffd2b5ed1c in Exiv2::Internal::PngChunk::decodeTXTChunk(Exiv2::Image*, Exiv2::DataBuf const&, Exiv2::Internal::PngChunk::TxtChunkType) ()
   from /usr/lib/libexiv2.so.13
#6  0x00007fffd2b62572 in Exiv2::PngImage::readMetadata() () from /usr/lib/libexiv2.so.13
#7  0x00007fffd310b01a in exiv2wrapper::Image::readMetadata() () from /usr/lib/python2.7/site-packages/libexiv2python.so
#8  0x00007fffd3117576 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (exiv2wrapper::Image::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, exiv2wrapper::Image&> > >::operator()(_object*, _object*) ()
   from /usr/lib/python2.7/site-packages/libexiv2python.so
#9  0x00007fffd2eb870a in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/libboost_python.so.1.55.0
#10 0x00007fffd2eb8a78 in ?? () from /usr/lib/libboost_python.so.1.55.0
#11 0x00007fffd2ec2f63 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const ()
   from /usr/lib/libboost_python.so.1.55.0
#12 0x00007fffd3117353 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Exiv2::BasicError<char>, void (*)(Exiv2::BasicError<char> const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Exiv2::BasicError<char> const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/site-packages/libexiv2python.so
#13 0x00007fffd2ec2d2d in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/libboost_python.so.1.55.0
#14 0x00007fffd2eb7383 in ?? () from /usr/lib/libboost_python.so.1.55.0
#15 0x00007fffe22736b3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#16 0x00007fffe2308a87 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#17 0x00007fffe2309fc3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#18 0x00007fffe230b970 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#19 0x00007fffe229849c in function_call () from /usr/lib/libpython2.7.so.1.0
#20 0x00007fffe22736b3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#21 0x00007fffe228260d in instancemethod_call () from /usr/lib/libpython2.7.so.1.0
#22 0x00007fffe22736b3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#23 0x00007fffe2273795 in call_function_tail () from /usr/lib/libpython2.7.so.1.0
#24 0x00007fffe2273aa7 in PyObject_CallMethod () from /usr/lib/libpython2.7.so.1.0
#25 0x00007fffe25f9f7c in ?? () from /usr/lib/nemo/extensions-3.0/libnemo-python.so
#26 0x00000000004c5765 in ?? ()
#27 0x00000000004c7622 in ?? ()
#28 0x00000000004cb282 in ?? ()
#29 0x00007ffff559a26b in ?? () from /usr/lib/libgio-2.0.so.0
#30 0x00007ffff559a8c6 in ?? () from /usr/lib/libgio-2.0.so.0
#31 0x00007ffff555d2c8 in ?? () from /usr/lib/libgio-2.0.so.0
#32 0x00007ffff5576bbd in ?? () from /usr/lib/libgio-2.0.so.0
#33 0x00007ffff559a26b in ?? () from /usr/lib/libgio-2.0.so.0
#34 0x00007ffff559a289 in ?? () from /usr/lib/libgio-2.0.so.0
#35 0x00007ffff500aa65 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#36 0x00007ffff500adc8 in ?? () from /usr/lib/libglib-2.0.so.0
#37 0x00007ffff500ae6c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#38 0x00007ffff55bc4cc in g_application_run () from /usr/lib/libgio-2.0.so.0
#39 0x000000000042b7a9 in ?? ()
#40 0x00007ffff4192000 in __libc_start_main () from /usr/lib/libc.so.6
#41 0x000000000042b7f3 in ?? ()
```

I believe it is nemo-media-columns because when I remove the extension, I can browse through the previously crashtastic directories.

**Comment by Daresch** [comment]
Eventually this is related to the issue #875 of nemo repository: https://github.com/linuxmint/nemo/issues/875

I have only problems with JPG files which are exported form Adobe Photoshop.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue.
